### ISSUE TITLE
建议加个处理速度的对比

### ISSUE THREAD

**Issue by canvascat** [tetap/yr_rust_konva#1]
感觉和直接用 konvajs 加滤镜速度差不多😆

**Comment by tetap** [comment]
简单的滤镜js执行会更快，例如灰度和二值化这种，复杂的算法下用wasm可以更快。konva有的算法并没有，我还要在写一份js版本做对比，有点麻烦。

**Comment by tetap** [comment]
我使用js也编写了一个扩散算法他们的差距接近一倍，这还只是两次遍历的简单算法，如果是更复杂的需要更多遍历的，效果会更加显著，如果你关注你的应用内存变化，那也会看到很大的变化。
![image](https://user-images.githubusercontent.com/57606461/197319004-794b91d7-5797-45ea-9b8d-0c745bbfd9c1.png)
